export const SUBTITLE_LANGUAGES = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "zh", name: "Chinese" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
]

export const SUBTITLE_FORMATS = [
  { id: "srt", label: "SRT (SubRip)" },
  { id: "vtt", label: "VTT (WebVTT)" },
  { id: "ass", label: "ASS (Advanced SubStation Alpha)" },
  { id: "lrc", label: "LRC (Lyrics)" },
]

export const VIDEO_FORMATS = [
  { id: "mp4-1080p", label: "MP4 1080p (HD)", size: "~120 MB per video", quality: "High" },
  { id: "mp4-720p", label: "MP4 720p (HD)", size: "~80 MB per video", quality: "Medium" },
  { id: "mp4-480p", label: "MP4 480p", size: "~40 MB per video", quality: "Low" },
]

export const AUDIO_FORMATS = [
  { id: "mp3-320", label: "MP3 320kbps", size: "~15 MB per video", quality: "High" },
  { id: "mp3-192", label: "MP3 192kbps", size: "~9 MB per video", quality: "Medium" },
  { id: "m4a", label: "M4A (AAC)", size: "~7 MB per video", quality: "Medium" },
]

export const SPONSORBLOCK_CATEGORIES = [
  { id: "sponsor", label: "Sponsor", description: "Paid promotions, paid referrals" },
  { id: "intro", label: "Intro", description: "Intro animations, sequences" },
  { id: "outro", label: "Outro", description: "Credits, end cards" },
  { id: "selfpromo", label: "Self Promotion", description: "Unpaid promotions of own products" },
  { id: "preview", label: "Preview", description: "Preview/recap of content" },
  { id: "filler", label: "Filler", description: "Tangential or filler content" },
  { id: "interaction", label: "Interaction", description: "Like/subscribe reminders" },
  { id: "music_offtopic", label: "Music: Non-Music", description: "Non-music sections in music videos" },
]

export const MOCK_VIDEO_INFO = {
  id: "dQw4w9WgXcQ",
  title: "Rick Astley - Never Gonna Give You Up (Official Music Video)",
  author: "Rick Astley",
  channelUrl: "https://www.youtube.com/@RickAstleyYT",
  lengthSeconds: 212,
  viewCount: "1.3B",
  uploadDate: "Oct 25, 2009",
  thumbnail: "/placeholder.svg?height=720&width=1280",
  description: 'The official music video for "Never Gonna Give You Up" by Rick Astley...',
  formats: [
    { id: "mp4-1080p", label: "MP4 1080p (HD)", size: "128 MB", quality: "High" },
    { id: "mp4-720p", label: "MP4 720p (HD)", size: "84 MB", quality: "Medium" },
    { id: "mp4-480p", label: "MP4 480p", size: "42 MB", quality: "Low" },
    { id: "mp4-360p", label: "MP4 360p", size: "28 MB", quality: "Low" },
  ],
  audioFormats: [
    { id: "mp3-320", label: "MP3 320kbps", size: "16 MB", quality: "High" },
    { id: "mp3-192", label: "MP3 192kbps", size: "10 MB", quality: "Medium" },
    { id: "m4a", label: "M4A (AAC)", size: "8 MB", quality: "Medium" },
    { id: "opus", label: "Opus", size: "7 MB", quality: "High" },
  ],
}

export const MOCK_PLAYLIST_INFO = {
  id: "PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI",
  title: "Top Music Videos 2023",
  author: "Music Channel",
  channelUrl: "https://www.youtube.com/@MusicChannel",
  videoCount: 12,
  viewCount: "2.4M",
  lastUpdated: "Updated 2 weeks ago",
  thumbnail: "/placeholder.svg?height=720&width=1280",
  description: "A collection of the most popular music videos of 2023...",
  videos: [
    {
      id: "video1",
      title: "Artist 1 - Popular Song (Official Video)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "3:45",
      author: "Artist 1",
      viewCount: "1.2M",
      selected: true,
    },
    {
      id: "video2",
      title: "Artist 2 - Summer Hit (Official Music Video)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "4:12",
      author: "Artist 2",
      viewCount: "850K",
      selected: true,
    },
    {
      id: "video3",
      title: "Artist 3 - Dance Track (Lyric Video)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "3:28",
      author: "Artist 3",
      viewCount: "620K",
      selected: true,
    },
    {
      id: "video4",
      title: "Artist 4 - Acoustic Session (Live)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "5:10",
      author: "Artist 4",
      viewCount: "430K",
      selected: true,
    },
    {
      id: "video5",
      title: "Artist 5 - New Release (Official Video)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "3:55",
      author: "Artist 5",
      viewCount: "780K",
      selected: true,
    },
    {
      id: "video6",
      title: "Artist 6 - Collaboration (feat. Artist 7)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "4:30",
      author: "Artist 6",
      viewCount: "920K",
      selected: true,
    },
    {
      id: "video7",
      title: "Artist 8 - Remix (Producer Version)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "3:15",
      author: "Artist 8",
      viewCount: "540K",
      selected: true,
    },
    {
      id: "video8",
      title: "Artist 9 - Viral Hit (TikTok Edition)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "2:45",
      author: "Artist 9",
      viewCount: "1.5M",
      selected: true,
    },
    {
      id: "video9",
      title: "Artist 10 - Comeback Single (2023)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "4:05",
      author: "Artist 10",
      viewCount: "670K",
      selected: true,
    },
    {
      id: "video10",
      title: "Artist 11 - Indie Track (Visualizer)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "3:50",
      author: "Artist 11",
      viewCount: "320K",
      selected: true,
    },
    {
      id: "video11",
      title: "Artist 12 - Debut Single (Official Video)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "3:30",
      author: "Artist 12",
      viewCount: "280K",
      selected: true,
    },
    {
      id: "video12",
      title: "Various Artists - Compilation (Highlights)",
      thumbnail: "/placeholder.svg?height=720&width=1280",
      duration: "6:15",
      author: "Music Channel",
      viewCount: "420K",
      selected: true,
    },
  ],
}

